package com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAndExceptionsAreGeneratedFromCodeNamesWhenCodeNameIsProvided_withNumber.code_9_name_c1.code_9_name_c2.code_9_name_c3_2;

import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAndExceptionsAreGeneratedFromCodeNamesWhenCodeNameIsProvided_withNumber.code_9_name_c1.code_9_name_c2.C2Exception;
import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAndExceptionsAreGeneratedFromCodeNamesWhenCodeNameIsProvided_withNumber.RootException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C3_2Exception extends C2Exception {



    protected C3_2Exception(String message) {
        super(message);
    }

    protected C3_2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
