package com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.error_name1.error_name2.error__name3_4__;

import com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.error_name1.error_name2.ErrorName2Exception;

/**
* Autogenerated by XGen on July 3, 2015.
*/
public class Error__Name3_4__Exception extends ErrorName2Exception {

    protected Error__Name3_4__Exception(String message) {
        super(message);
    }
}
