package com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.error_name1.error_name2.error__name__9__name3_4__;

import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.error_name1.error_name2.ErrorName2Exception;
import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.RootNameException;
import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class Error__Name__9__Name3_4__Exception extends ErrorName2Exception {

    public static final ExceptionType TYPE = new ExceptionType();

    protected Error__Name__9__Name3_4__Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected Error__Name__9__Name3_4__Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }

    private static class ExceptionType extends RootNameException.ExceptionType {

        @Override
        protected RootNameException createException(ErrorCode errorCode, String message) {
            return new Error__Name__9__Name3_4__Exception(errorCode, message);
        }

        @Override
        protected RootNameException createException(ErrorCode errorCode, String message, Throwable cause) {
            return new Error__Name__9__Name3_4__Exception(errorCode, message, cause);
        }
    }
}
